[build]
  command = "cd backend && npm install"
  publish = "."

[functions]
  directory = "netlify"
  external_node_modules = ["express", "dotenv", "mysql2", "jsonwebtoken"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200